create table if not exists listings (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'master_20' check (type in ('master_20', 'concours_ecole')),
  university_id uuid not null references universities(id) on delete cascade,
  domain_id uuid references domains(id) on delete set null,
  faculty_fr text,
  faculty_ar text,
  specialty_fr text not null,
  specialty_ar text,
  level text check (level in ('M1', 'M2')),
  required_license_fields text,
  seats_available int,
  academic_year text not null,
  application_start_date date,
  application_deadline date not null,
  portal_url text not null,
  source_url text,
  notes_fr text,
  notes_ar text,
  is_published boolean not null default true,
  last_verified_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
